# <b><div style='padding:15px;background-color:#d8dcd6;color:#030aa7;font-size:120%;text-align: left'>Récapitulatif des fichiers de données</div></b>

In [1]:
!ls -al /opt/spark/donnees

total 76888
drwxrwsr-x 8 spark root      4096 Oct 18 08:22 .
drwxr-xr-x 1 spark spark     4096 Oct 18 08:45 ..
drwxrwsr-x 2 spark root      4096 Oct 18 07:57 ebrasil
-rw-rw-r-- 1 spark root    940317 Oct 18 07:57 export_sql.parquet
drwxrwsr-x 2 spark root      4096 Oct 18 07:57 input
drwxrwsr-x 2 spark root      4096 Oct 18 07:57 logs
drwxrwsr-x 2 spark root      4096 Oct 18 07:57 log_web_access
drwxrwsr-x 2 spark root      4096 Oct 18 07:57 meteo
-rw-rw-r-- 1 spark root  28676943 Oct 18 07:57 meteo.gzip
-rw-rw-r-- 1 spark root  32797342 Oct  2 16:03 meteoParquet.gzip
drwxrwsr-x 2 spark root      4096 Oct 18 07:57 opendata
-rw-rw-r-- 1 spark root      2618 Oct 18 07:57 postesSynop.csv
-rw-rw-r-- 1 spark root      3456 Oct 18 07:57 README.md
-rw-rw-r-- 1 spark root  16266066 Oct 18 07:57 Web.Server.Access10.gzip

In [2]:
!ls -al /opt/spark/donnees/ebrasil

total 110948
drwxrwsr-x 2 spark root     4096 Oct 18 07:57 .
drwxrwsr-x 8 spark root     4096 Oct 18 08:22 ..
-rw-rw-r-- 1 spark root  9033957 Oct 18 07:57 olist_customers_dataset.csv
-rw-rw-r-- 1 spark root 48714816 Oct 18 07:57 olist_geolocation_dataset.csv
-rw-rw-r-- 1 spark root 15438671 Oct 18 07:57 olist_order_items_dataset.csv
-rw-rw-r-- 1 spark root  5777138 Oct 18 07:57 olist_order_payments_dataset.csv
-rw-rw-r-- 1 spark root 14409007 Oct 18 07:57 olist_order_reviews_dataset.csv
-rw-rw-r-- 1 spark root 17654914 Oct 18 07:57 olist_orders_dataset.csv
-rw-rw-r-- 1 spark root  2379446 Oct 18 07:57 olist_products_dataset.csv
-rw-rw-r-- 1 spark root   174703 Oct 18 07:57 olist_sellers_dataset.csv
-rw-rw-r-- 1 spark root     2542 Oct 18 07:57 product_category_name_translation.csv

In [3]:
!ls -al /opt/spark/donnees/meteo

total 143612
drwxrwsr-x 2 spark root    4096 Oct 18 07:57 .
drwxrwsr-x 8 spark root    4096 Oct 18 08:22 ..
-rw-rw-r-- 1 spark root 4189020 Oct 18 07:57 synop.202301.csv
-rw-rw-r-- 1 spark root 3626128 Oct 18 07:57 synop.202302.csv
-rw-rw-r-- 1 spark root 4105061 Oct 18 07:57 synop.202303.csv
-rw-rw-r-- 1 spark root 4041942 Oct 18 07:57 synop.202304.csv
-rw-rw-r-- 1 spark root 4203446 Oct 18 07:57 synop.202305.csv
-rw-rw-r-- 1 spark root 4083804 Oct 18 07:57 synop.202306.csv
-rw-rw-r-- 1 spark root 4098443 Oct 18 07:57 synop.202307.csv
-rw-rw-r-- 1 spark root 4215978 Oct 18 07:57 synop.202308.csv
-rw-rw-r-- 1 spark root 4054875 Oct 18 07:57 synop.202309.csv
-rw-rw-r-- 1 spark root 4107655 Oct 18 07:57 synop.202310.csv
-rw-rw-r-- 1 spark root 4009103 Oct 18 07:57 synop.202311.csv
-rw-rw-r-- 1 spark root 4186069 Oct 18 07:57 synop.202312.csv
-rw-rw-r-- 1 spark root 4164769 Oct 18 07:57 synop.202401.csv
-rw-rw-r-- 1 spark root 3865487 Oct 18 07:57 synop.202402.csv
-rw-rw-r-- 1 spark root 4229957 Oct 18 07:57 synop.202403.csv
-rw-rw-r-- 1 spark root 4096596 Oct 18 07:57 synop.202404.csv
-rw-rw-r-- 1 spark root 4270333 Oct 18 07:57 synop.202405.csv
-rw-rw-r-- 1 spark root 4090948 Oct 18 07:57 synop.202406.csv
-rw-rw-r-- 1 spark root 4191109 Oct 18 07:57 synop.202407.csv
-rw-rw-r-- 1 spark root 4201423 Oct 18 07:57 synop.202408.csv
-rw-rw-r-- 1 spark root 4047347 Oct 18 07:57 synop.202409.csv
-rw-rw-r-- 1 spark root 4125068 Oct 18 07:57 synop.202410.csv
-rw-rw-r-- 1 spark root 4009275 Oct 18 07:57 synop.202411.csv
-rw-rw-r-- 1 spark root 4168390 Oct 18 07:57 synop.202412.csv
-rw-rw-r-- 1 spark root 4143578 Oct 18 07:57 synop.202501.csv
-rw-rw-r-- 1 spark root 3684501 Oct 18 07:57 synop.202502.csv
-rw-rw-r-- 1 spark root 4073763 Oct 18 07:57 synop.202503.csv
-rw-rw-r-- 1 spark root 3915948 Oct 18 07:57 synop.202504.csv
-rw-rw-r-- 1 spark root 4126452 Oct 18 07:57 synop.202505.csv
-rw-rw-r-- 1 spark root 3932512 Oct 18 07:57 synop.202506.csv
-rw-rw-r-- 1 spark root 4111781 Oct 18 07:57 synop.202507.csv
-rw-rw-r-- 1 spark root 4082704 Oct 18 07:57 synop.202508.csv
-rw-rw-r-- 1 spark root 4005894 Oct 18 07:57 synop.202509.csv
-rw-rw-r-- 1 spark root 4214397 Oct 18 07:57 synop.202510.csv
-rw-rw-r-- 1 spark root 4069074 Oct 18 07:57 synop.202511.csv
-rw-rw-r-- 1 spark root 4238763 Oct 18 07:57 synop.202512.csv

In [4]:
!ls -al /opt/spark/donnees/logs

total 100
drwxrwsr-x 2 spark root  4096 Oct 18 07:57 .
drwxrwsr-x 8 spark root  4096 Oct 18 08:22 ..
-rw-rw-r-- 1 spark root 69266 Oct 18 07:57 access.log
-rw-rw-r-- 1 spark root 22315 Oct 18 07:57 application.log

In [5]:
!ls -al /opt/spark/donnees/log_web_access

total 154352
drwxrwsr-x 2 spark root     4096 Oct 18 07:57 .
drwxrwsr-x 8 spark root     4096 Oct 18 08:22 ..
-rw-rw-r-- 1 spark root 15384721 Oct 18 07:57 access_01.log
-rw-rw-r-- 1 spark root 15732676 Oct 18 07:57 access_02.log
-rw-rw-r-- 1 spark root 15665101 Oct 18 07:57 access_03.log
-rw-rw-r-- 1 spark root 15667678 Oct 18 07:57 access_04.log
-rw-rw-r-- 1 spark root 15909065 Oct 18 07:57 access_05.log
-rw-rw-r-- 1 spark root 16035576 Oct 18 07:57 access_06.log
-rw-rw-r-- 1 spark root 16029802 Oct 18 07:57 access_07.log
-rw-rw-r-- 1 spark root 15630451 Oct 18 07:57 access_08.log
-rw-rw-r-- 1 spark root 15958816 Oct 18 07:57 access_09.log
-rw-rw-r-- 1 spark root 16007347 Oct 18 07:57 access_10.log

In [6]:
!ls -al /opt/spark/donnees/input

total 188
drwxrwsr-x 2 spark root   4096 Oct 18 07:57 .
drwxrwsr-x 8 spark root   4096 Oct 18 08:22 ..
-rw-rw-r-- 1 spark root   5677 Oct 18 07:57 catalog.xlsx
-rw-rw-r-- 1 spark root  13952 Oct 18 07:57 customers.json
-rw-rw-r-- 1 spark root 159342 Oct 18 07:57 sales.csv

In [7]:
!ls -al /opt/spark/donnees/opendata

total 12
drwxrwsr-x 2 spark root 4096 Oct 18 07:57 .
drwxrwsr-x 8 spark root 4096 Oct 18 08:22 ..
-rw-rw-r-- 1 spark root  452 Oct 18 07:57 sample.json

# <b><div style='padding:15px;background-color:#d8dcd6;color:#030aa7;font-size:120%;text-align: left'>Base de données `formation`</div></b>

In [8]:
import sqlalchemy, pandas as pd
from sqlalchemy import text
from sqlalchemy.engine import URL


url = URL.create(
    drivername="postgresql+psycopg2",
    username="formation",
    password="formation",
    host="postgres-source",
    port=5432,
    database="formation",
)

engine = sqlalchemy.create_engine( 
    url, #url = "postgresql://formation:formation@postgres-source:5432/formation"
    pool_pre_ping=True,
)

with engine.connect() as connexion:
    print(connexion.execute(text("SELECT current_database(), current_user")).fetchone())

connection = engine.connect()

('formation', 'formation')

In [9]:
requete  = "select * from customers"
pd.read_sql_query(requete, connection)

,customer_id,first_name,last_name,country,segment,created_at
0,1,Alice,Martin,FR,Retail,2026-10-18 08:44:53.867851+00:00
1,2,Benoit,Durand,FR,SMB,2026-10-18 08:44:53.867851+00:00
2,3,Clara,Bernard,BE,Enterprise,2026-10-18 08:44:53.867851+00:00
3,4,David,Muller,DE,Retail,2026-10-18 08:44:53.867851+00:00
4,5,Eva,Rossi,IT,SMB,2026-10-18 08:44:53.867851+00:00

In [10]:
requete  = "select * from order_lines"
pd.read_sql_query(requete, connection)

   order_id  product_id  quantity  unit_price
0      1001         101         1      1299.0
1      1001         103         1        79.0
2      1002         102         2       349.0
3      1003         105         4       159.0
4      1004         104         3        49.0
5      1005         103         2        79.0

In [11]:
requete  = "select * from orders"
pd.read_sql_query(requete, connection)

   order_id  customer_id                         order_ts   status    source
0      1001            1 2026-10-13 08:44:53.871185+00:00     PAID  postgres
1      1002            2 2026-10-15 08:44:53.871185+00:00     PAID  postgres
2      1003            3 2026-10-17 08:44:53.871185+00:00  SHIPPED  postgres
3      1004            1 2026-10-18 02:44:53.871185+00:00     PAID  postgres
4      1005            5 2026-10-18 07:44:53.871185+00:00      NEW  postgres

In [12]:
requete  = "select * from products"
pd.read_sql_query(requete, connection)

   product_id product_name     category  unit_price
0         101   Laptop Pro    Computers      1299.0
1         102   Monitor 27     Displays       349.0
2         103     Keyboard  Accessories        79.0
3         104        Mouse  Accessories        49.0
4         105   Dock USB-C  Accessories       159.0

# <b><div style='padding:15px;background-color:#d8dcd6;color:#030aa7;font-size:120%;text-align: left'>Base de données `ebrasil`</div></b>

In [13]:
url = sqlalchemy.URL.create(
        drivername="postgresql+psycopg2",
        username="formation",
        password="formation",
        host="postgres-source",
        port=5432,
        database="ebrasil",
    )


engine = sqlalchemy.create_engine( 
    url, #url = "postgresql://formation:formation@postgres-source:5432/formation"
    pool_pre_ping=True,
)
print("connecting with engine " + str(engine))

connection = engine.connect()    

with engine.connect() as connection:
    print(connection.execute(sqlalchemy.text("SELECT current_database(), current_user")).fetchone())

connecting with engine Engine(postgresql+psycopg2://formation:***@postgres-source:5432/ebrasil)
('ebrasil', 'formation')

<img src="https://raw.githubusercontent.com/rbizoi/FormationBigDataBI/refs/heads/master/images/ebrasil.png" width="850">

In [14]:
requete  = """
            select 'orders     ' table, count(*) enregistrements      from orders       
            union all
            select 'customers  ' , count(*) from customers    
            union all
            select 'sellers    ' , count(*) from sellers      
            union all
            select 'items      ' , count(*) from items        
            union all
            select 'payments   ' , count(*) from payments     
            union all
            select 'reviews    ' , count(*) from reviews      
            union all
            select 'reviews_p  ' , count(*) from reviews_p    
            union all
            select 'products   ' , count(*) from products     
            union all
            select 'geolocation' , count(*) from geolocation"""
with engine.connect() as connection:
    print(pd.read_sql_query(requete, connection))

         table  enregistrements
0  sellers                 3095
1  geolocation            19177
2  products               32951
3  payments              103886
4  customers              99441
5  reviews               100000
6  reviews_p              99441
7  items                 112650
8  orders                 99441